### ISSUE TITLE
nix instead ppa to install GHC, cabal?

### ISSUE THREAD

**Issue by kanishka-azimi** [haskell-hvr/multi-ghc-travis#102]
What do you think about switching to using nix for the installation of ghc and cabal only? Then proceeding to use installed cabal without nix. I might be overlooking something obvious.

**Comment by phadej** [comment]
One things is that @hvr pushes GHC release candidates and HEAD, as well as `cabal-install-head` into the PPA, which scripts from this repository use.

So there is a strong dogfooding going on.

**Comment by hvr** [comment]
@kanishka-azimi what would be the benefit of using Nix over the PPA here? What's the oldest GHC supported by Nix btw? Does Nix provide binaries of GHCs compiled specifically for Ubuntu LTS releases (precise, trusty, xenial)?

**Comment by kanishka-azimi** [comment]
Possibly Centos and Red Hat support? Possibly that nix provides multiple
GHC's as part of it's core, so their wouldn't be as much need for custom
built packages or a ppa. I don't have a strong reason and I only have
beginner experience with nix, just curious.

I will try to do a diff between the ppa build settings and the nix package
build settings for GHC here, for us to see.

**Comment by kanishka-azimi** [comment]
Haven't gotten around to the diff yet. I will close, for lack of providing more useful detail for a while now.
