### ISSUE TITLE
Enable profiling?

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell-hvr/multi-ghc-travis#131]
I'd like to build with the profiling versions of boot libraries (base, etc) installed. What would be the appropriate place to install them?

**Comment by phadej** [comment]
Do you want to build in Travis with profiling libraries (I wonder why, travis isn't good environment for performance testing).

Or if you asking about hvr-ppa, then there are `ghc-8.2.2-prof`, `ghc-8.0.2-prof` etc. packages.

**Comment by mitchellwrosen** [comment]
Great, those packages are exactly what I need. I'm not doing performance testing in Travis, just testing some parsing of `+RTS -S` output and such. Thanks.
