### ISSUE TITLE
use  -j 1 for cabal build?

### ISSUE THREAD

**Issue by jwaldmann** [haskell-hvr/multi-ghc-travis#42]
About the role of (missing/defaulted) `-j` option for the cabal commands, see
https://ghc.haskell.org/trac/ghc/ticket/10818#comment:15

**Comment by hvr** [comment]
If you notice https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml.hs#L128 this is already being taken care of... :-)

**Comment by phadej** [comment]
Now one can configure both `-j` for cabal and ghc, with `--jobs N:M`
