### ISSUE TITLE
Support for multipackage projects

### ISSUE THREAD

**Issue by cocreature** [haskell-hvr/multi-ghc-travis#56]
It would be nice if there was builtin support for projects consisting of multiple cabal packages. This should be quite easy using `cabal new-build`. We only need to
- Parse the `cabal.project` file to find the individual cabal files (I think it’s reasonable to assume that one exists).
- Add all the targets to the build command.
- Search for tests separately for each cabal project.

I’ll try to make a PR when I have time, but I can’t promise that it will be anytime soon.

**Comment by hvr** [comment]
related: https://github.com/haskell/cabal/issues/3391

**Comment by merijn** [comment]
Whoops, completely missed this issue. This is fixed by #97.

**Comment by phadej** [comment]
Thanks @merijn
