### ISSUE TITLE
commenting out jobs in cabal.config results in super slowdown

### ISSUE THREAD

**Issue by zilinc** [haskell-hvr/multi-ghc-travis#74]
I don't have any insights here, but just from my experiments, I found if I commented out the jobs line in cabal.config file, the building time increased from ~34mins to 50+mins which timed out. See: https://travis-ci.org/NICTA/cogent/builds (build 113 vs. 114).

**Comment by hvr** [comment]
That's quite possible. In the next-gen travis script generator, I tend to set jobs to `2`, as that seems to match the Travis buildbot configuration a bit better.

**Comment by zilinc** [comment]
And I'm not sure if the excessively verbose output (https://github.com/haskell/cabal/issues/1554) when no `jobs` line is present is also a contributing factor to the slowness.

**Comment by phadej** [comment]
I think we could have `-j2`, but we'd need non-interleaved output from cabal for that... It's super confusing otherwise.

**Comment by phadej** [comment]
You can use `--jobs 2` (or `--jobs 2:2` etc.) to set parallelism levels. See  https://github.com/haskell-hvr/multi-ghc-travis/pull/115
